# -*- coding: utf-8 -*-
"""Untitled65.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14uk49u8YgL-wzAw-kI7b0k0R73Vn62sZ

**Anamoly Detection  using Isolation Forest Algorithm**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('Credit.csv')
df=df.drop(columns=['Class'])
df=df.dropna(how='any')
display(df)

X=df.iloc[:,:-1].values
Y=df.iloc[:,-1].values

Y=Y.reshape(len(Y),1)
Y

from sklearn.ensemble import IsolationForest
forest_model=IsolationForest(max_features = 1.0,n_estimators=100, max_samples='auto',contamination=float(0.2))
forest_model.fit(Y)

df['scores']=forest_model.decision_function(Y)
df['anomaly_Value']=forest_model.predict(Y)
df.head(10)

"""Evaluation Of model"""

oc=len(df[df['Amount']>80])
oc

print("Accuracy percentage:", 100*list(df['anomaly_Value']).count(-1)/(oc))